name: Deploy dan-plugin-patentstyret

on:
 push:
   branches: [ main ]
   paths-ignore:
     - '**/README.md'
     - '**/*.yml'
 workflow_dispatch:

jobs:
 run:
  permissions:
    actions: read
    contents: read
  uses: data-altinn-no/deploy-actions/.github/workflows/dan-deploy-flow.yml@c4015d6075f12d8389be1136e40ef961056270de
  with:
    artifact_name: 'dan-plugin-patentstyret' # Can be omitted, defaults to 'artifact'
    function_project_path: 'src/Dan.Plugin.Patentstyret'
  secrets:
    function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
    publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
    azure_artifact_pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}
    azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    resource_group_prod: ${{ secrets.RESOURCE_GROUP_PROD }}
